#!/usr/bin/env python3
# -*- coding: utf-8 -*-

## weather_types.py


weather_icon = {"Nuit claire": "soleil",
                "Ensoleillé": "soleil",
                "Ciel voilé ": "ciel_voile",
                "Éclaircies": "eclaircie",
                "Très nuageux": "tres_nuageux",
                "Brume ou bancs de brouillard": "brouillard",
                "Brouillard": "brouillard",
                "Brouillard givrant": "brouillard_givrant",
                "Pluie faible": "pluie_faible",
                "Rares averses": "pluie_faible",
                "Pluies éparses / Rares averses": "pluie_faible",
                "Pluies orageuses": "pluies_orageuses",
                "Pluie orageuse": "pluies_orageuses",
                "Averses orageuses": "pluies_orageuses",
                "Pluies éparses": "pluie_eparse",
                "Averses": "pluie_averses",
                "Pluie": "pluie_averses",
                "Pluie verglaçante": "pluie_verglassante",
                "Pluie / Averses": "pluie_averses",
                "Pluie forte": "pluie_forte",
                "Quelques flocons": "quelques_flocons",
                "Pluie et neige": "pluie_et_neige",
                "Neige / Averses de neige": "neige",
                "Neige forte": "neige_forte",
                "Risque de grêle": "risque_de_grele",
                "Risque d’orages": "risque_d_orages",
                "Orages":  "orages",
                "Risques d'orages": "risque_d_orages",
                "Risque d'orages": "risque_d_orages",
                None: None,
                "$prev.tempsSensible": None}

##icons_note = {  "soleil":  0,
                ##"ciel_voile":  1,
                ##"eclaircie":  2,
                ##"tres_nuageux":  3,
                ##"brouillard":  4,
                ##"brouillard_givrant":  5,
                ##"pluie_faible":  6,
                ##"pluies_orageuses":  7,
                ##"pluie_eparse":  8,
                ##"pluie_averses":  9,
                ##"pluie_verglassante":  10,
                ##"pluie_forte":  11,
                ##"quelques_flocons":  12,
                ##"pluie_et_neige":  13,
                ##"neige":  14,
                ##"neige_forte":  15,
                ##"risque_de_grele":  16,
                ##"risque_d_orages":  17,
                ##"orages":  18,
                ##"risque_d_orages":  19,
                ##None: 20 }
