#!/usr/bin/env python3
# -*- coding: utf-8 -*-

## weather_types.py


weather_icon = {"Nuit claire": "soleil",
                "Ensoleillé": "soleil",
                "Ciel voilé ": "ciel_voile",
                "Éclaircies": "eclaircie",
                "Très nuageux": "tres_nuageux",
                "Brume ou bancs de brouillard": "brouillard",
                "Brouillard": "brouillard",
                "Brouillard givrant": "brouillard_givrant",
                "Pluie faible": "pluie_faible",
                "Rares averses": "pluie_faible",
                "Pluies éparses / Rares averses": "pluie_faible",
                "Pluies orageuses": "pluies_orageuses",
                "Pluie orageuse": "pluies_orageuses",
                "Averses orageuses": "pluies_orageuses",
                "Pluies éparses": "pluie_eparse",
                "Averses": "pluie_averses",
                "Pluie": "pluie_averses",
                "Pluie verglaçante": "pluie_verglassante",
                "Pluie / Averses": "pluie_averses",
                "Pluie forte": "pluie_forte",
                "Quelques flocons": "quelques_flocons",
                "Pluie et neige": "pluie_et_neige",
                "Neige / Averses de neige": "neige",
                "Neige forte": "neige_forte",
                "Risque de grêle": "risque_de_grele",
                "Risque d’orages": "risque_d_orages",
                "Orages":  "orages",
                "Risques d'orages": "risque_d_orages",
                "Risque d'orages": "risque_d_orages",
                "Bancs de brouillard": "",
                "Brume": "brume",
                "Neige": "neige",
                "Brouillard Givrant": "brouillard_givrant",
                "Averses de neige": "averses_de_neige",
                None: None,
                "$prev.tempsSensible": None}
